[package]
name = "tracing-actix-web-mozlog"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "^0.4"
gethostname = "^0.2"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tracing = "^0.1"
tracing-bunyan-formatter = "^0.2"
tracing-subscriber = "^0.2"
actix-web = "=4.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-http = "=3.0.0-beta.5"
tracing-actix-web = { version = "=0.4.0-beta.4", default-features = false }

[dev-dependencies]
maplit = "^1"
pretty_assertions = "^0.7"
jsonschema = "^0.9"
lazy_static = "^1.4"
actix-rt = "^2.2.0"
tracing-futures = { version = "^0.2", features = ["std-future"] }
